name: Build, Publish & Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run type-check

      - name: Build package
        run: npm run build

      - name: Check version changed
        id: version-check
        run: |
          git fetch --tags
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          if git rev-parse "v$CURRENT_VERSION" >/dev/null 2>&1; then
            echo "version_changed=false" >> $GITHUB_OUTPUT
            echo "Version v$CURRENT_VERSION already exists"
          else
            echo "version_changed=true" >> $GITHUB_OUTPUT
            echo "New version v$CURRENT_VERSION detected"
          fi

      - name: Publish to npm
        if: steps.version-check.outputs.version_changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Git tag
        if: steps.version-check.outputs.version_changed == 'true'
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "v$CURRENT_VERSION" -m "Release v$CURRENT_VERSION"
          git push origin "v$CURRENT_VERSION"

      - name: Create GitHub Release
        if: steps.version-check.outputs.version_changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version-check.outputs.CURRENT_VERSION }}
          release_name: Release v${{ steps.version-check.outputs.CURRENT_VERSION }}
          body: |
            See [CHANGELOG.md](https://github.com/parth181195/ffmpeg-forge/blob/main/CHANGELOG.md) for details.
          draft: false
          prerelease: false

      - name: Build documentation
        run: npm run docs:build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

